package:
  name: control_cluster_utils
  version: 0.0.1

source:
  path: .

requirements:
  build:
    - python 3.7
    - setuptools

build:
  script:
    - python3 -m pip install -v .

about:
  home: https://github.com/AndPatr/ControlClusterUtils
  license: MIT
  summary: Utilities to create a CPU-based controllers cluster to be interfaced with GPU-based simulators 
