package:
  name: control_cluster_utils
  version: '1.0_py{{ py }}'

source:
  path: .

requirements:
  build:
    - python 3.7
    - setuptools

build:
  script:
    - python3 -m pip install -v .

about:
  home: https://github.com/AndrePatri/ControlClusterUtils
  license: MIT
  summary: Utilities to create a CPU-based control cluster to be interfaced with GPU-based simulators using shared memory for minimum latency.